INSERT INTO USERS (USER_ID, USER_NAME, USER_PASSWORD, EMAIL, COUNTRY, HOME_ADDRESS) VALUES (1,'Mencia','102030K','menciasanchez@gmail.com','Spain', 'Calle Mirador 8');
INSERT INTO USERS (USER_ID, USER_NAME, USER_PASSWORD, EMAIL, COUNTRY, HOME_ADDRESS) VALUES (2,'Lola','LolaMola2','lolaroca@gmail.com','Spain', 'Calle Duque 10');

INSERT INTO PAGAR (USER_ID, PRICE) VALUES (1,10);
INSERT INTO PAGAR (USER_ID, PRICE) VALUES (2,15);

INSERT INTO DISCOUNT (USER_ID, DISCOUNT_ID, PRICE_DISCOUNT) VALUES (2,28,5);
INSERT INTO DISCOUNT (USER_ID, DISCOUNT_ID, PRICE_DISCOUNT) VALUES (1,20,8);